# Site settings
title: *blog
email: mholub.ethz=gmail+comm
description: > # this means to ignore newlines until "baseurl:"
  A simple, whitespace, helvetica based portfolio theme.
baseurl:  # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
twitter_username: scimartinx
github_username:  martinholub

repository: martinholub/martin-holub.github.io
github: [metadata]
exclude: [Rakefile]
include: [pages]

plugins:
    - jekyll-paginate
    - jekyll-feed
    - jekyll-github-metadata
    - jekyll-twitter-plugin
    - github-pages
    - jekyll-jupyter-notebook
    - jekyll-gist
    - jekyll-font-awesome-sass

plugins_dir: ./_plugins

# sass
#sass:
#    sass_dir: css/_sass

#font awesome
font-awesome:
  assets: true

# Defaults
defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      comments: true
      sharing: true
      published: true

# Build settings
markdown: kramdown #redcarpet
highlighter: pygments #pygments
kramdown:
  input: GFM
  syntax_highlighter_opts:
    default_lang: html
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false # https://flinhong.com/2017/03/18/syntax-highlight-with-rouge-in-jekyll/
      start_line: 1

# Pagination
paginate: 3
paginate_path: "/blog/page:num/"
pagination_enabled?: 1

# Teasers
excerpt_separator: <!---break--->

collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  research:
    output: true
    permalink: /research/:path/
#  poetry:
#   output: false
#    permalink: /poetry/:path/

JB :
  version : 0.3.0
  BASE_PATH : false
  ASSET_PATH : false

  # Settings for comments helper
  # Set 'provider' to the comment provider you want to use.
  # Set 'provider' to false to turn commenting off globally.
  #
  comments :
    provider : disqus
    disqus :
      layout : default
      short_name : martinholub
    livefyre :
      site_id : 123
    intensedebate :
      account : 123abc
    facebook :
      appid : 123
      num_posts: 5
      width: 580
      colorscheme: dark
    duoshuo :
      short_name : jekyllbootstrap
  # Settings for analytics helper
  # Set 'provider' to the analytics provider you want to use.
  # Set 'provider' to false to turn analytics off globally.
  #
  analytics :
    provider : google
    gauges :
        site_id : 'SITE ID'
    google :
        tracking_id : 'G-1ZBQKKLMRB'
    getclicky :
      site_id :
    mixpanel :
        token : '_MIXPANEL_TOKEN_'
    piwik :
        baseURL : 'myserver.tld/piwik' # Piwik installation address (without protocol)
        idsite : '1'                   # the id of the site on Piwik

  # Settings for sharing helper.
  # Sharing is for things like tweet, plusone, like, reddit buttons etc.
  # Set 'provider' to the sharing provider you want to use.
  # Set 'provider' to false to turn sharing off globally.
  #
  sharing :
    provider : false

  # Settings for all other include helpers can be defined by creating
  # a hash with key named for the given helper. ex:
  #
  #   pages_list :
  #     provider : "custom"
  #
  # Setting any helper's provider to 'custom' will bypass the helper code
  # and include your custom code. Your custom file must be defined at:
  #   ./_includes/custom/[HELPER]
  # where [HELPER] is the name of the helper you are overriding.

  # RSS Feed
  feed_meta:
    name: Martin Holub Blog
    title: Martin Holub Blog
    description: Personal Blog
    author: Martin Holub
    url: https://www.martinholub.com/
